const colors = {
  light: {
    text: "#0F0F0F",
    tint: "#FF6B35",
    background: "#F5F5F5",
    foreground: "#0F0F0F",
    card: "#FFFFFF",
    cardForeground: "#0F0F0F",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F0",
    secondaryForeground: "#1A1A1A",
    muted: "#F0F0F0",
    mutedForeground: "#737373",
    accent: "#30D158",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5E5",
    input: "#E5E5E5",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF6B35",
    background: "#0F0F0F",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#252525",
    secondaryForeground: "#EBEBF5",
    muted: "#252525",
    mutedForeground: "#8E8E93",
    accent: "#30D158",
    accentForeground: "#0F0F0F",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#2C2C2E",
    input: "#2C2C2E",
  },
  radius: 16,
};

export default colors;
