version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && pip install -r src/requirements.txt
      - cd $CODEBUILD_SRC_DIR/backend && pip install -r tests/requirements.txt
  
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && sam validate -t template.yaml
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export AUTO_BUCKET="fitness-tracker-sam-artifacts-${ACCOUNT_ID}"
      - aws s3 mb s3://${AUTO_BUCKET} --region ap-southeast-2 || echo "Bucket already exists"

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && python -m pytest --cov=src --cov-fail-under=80 --cov-report=xml --junitxml=reports/junit.xml tests/
      - cd $CODEBUILD_SRC_DIR/backend && sam build -t template.yaml

  post_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export AUTO_BUCKET="fitness-tracker-sam-artifacts-${ACCOUNT_ID}"
      - cd $CODEBUILD_SRC_DIR/backend && sam package --template-file .aws-sam/build/template.yaml --s3-bucket ${AUTO_BUCKET} --region ap-southeast-2 --output-template-file packaged-template.yaml

reports:
  pytest_reports:
    files:
      - backend/reports/junit.xml
    file-format: JUNITXML

artifacts:
  base-directory: backend
  files:
    - packaged-template.yaml
