version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && pip install -r src/requirements.txt
      - cd $CODEBUILD_SRC_DIR/backend && pip install -r tests/requirements.txt
  
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && sam validate -t template.yaml

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && python -m pytest --cov=src --cov-fail-under=80 --cov-report=xml --junitxml=reports/junit.xml tests/
      - cd $CODEBUILD_SRC_DIR/backend && sam build -t template.yaml

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/backend && sam package --template-file .aws-sam/build/template.yaml --s3-bucket $SAM_ARTIFACT_BUCKET --output-template-file packaged-template.yaml

reports:
  pytest_reports:
    files:
      - backend/reports/junit.xml
    file-format: JUNITXML

artifacts:
  base-directory: backend
  files:
    - packaged-template.yaml
